[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shdw-node-stats"
version = "0.2.3"
description = "A tool to fetch and record ShadowDrive node statistics from an API and save them to a CSV file."
authors = [{ name = "AnyNodes", email = "anynodes@outlook.com" }]
readme = "README.md"
license = { text = "MIT" }
keywords = ["API", "ShadowDrive", "statistics", "CSV", "shdw", "solana", "storage"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.25.1"
]

[project.scripts]
node-stats = "NodeStats.py"

[project.urls]
homepage = "https://github.com/AnyNodes/shdw-node-stats#readme"
issues = "https://github.com/AnyNodes/shdw-node-stats/issues"
repository = "https://github.com/AnyNodes/shdw-node-stats.git"

[tool.semantic_release]
version_variable = "pyproject.toml:project.version"
version_toml = ["pyproject.toml:project.version"]
branch = "main"
upload_to_pypi = "true"
commit_parser = "angular"
commit_version_number = "true"
commit_author = "semantic-release <semantic-release>"
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
# build_command = """
#     python -m pip install twine build~=0.10.0
#     python -m build .
#     twine upload dist/*
# """

[tool.semantic_release.commit_parser_options]
allowed_tags = [
  "build",
  "chore",
  "ci",
  "docs",
  "feat",
  "fix",
  "perf",
  "style",
  "refactor",
  "test",
]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
